### ISSUE TITLE
daily inmate pop upload messy and redundant

### ISSUE THREAD

**Issue by bfeldman89** [bfeldman89/mdoc_scraper#14]
<img width="529" alt="Screen Shot 2022-07-01 at 5 06 51 PM" src="https://user-images.githubusercontent.com/26087892/176972981-0b9d959f-012a-4090-a528-69c7e8cbb2bc.png">

**Comment by bfeldman89** [comment]
Traceback (most recent call last):
  File "/home/bfeldman89/.virtualenvs/mdoc_scraper-Qob3084f/lib/python3.8/site-packages/documentcloud/client.py", line 164, in raise_for_status
    response.raise_for_status()
  File "/home/bfeldman89/.virtualenvs/mdoc_scraper-Qob3084f/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.beta.documentcloud.org/api/documents/22084993/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mdoc_scraper.py", line 81, in <module>
    main()
  File "mdoc_scraper.py", line 77, in main
    scrape_mdoc_stuff('https://www.mdoc.ms.gov/Admin-Finance/Pages/Daily-Inmate-Population.aspx', 'daily_population')
  File "mdoc_scraper.py", line 66, in scrape_mdoc_stuff
    obj = upload_to_documentcloud(this_dict['url'], this_dict, dc_data)
  File "mdoc_scraper.py", line 22, in upload_to_documentcloud
    obj.put()
  File "/home/bfeldman89/.virtualenvs/mdoc_scraper-Qob3084f/lib/python3.8/site-packages/documentcloud/base.py", line 177, in put
    return self.save()
  File "/home/bfeldman89/.virtualenvs/mdoc_scraper-Qob3084f/lib/python3.8/site-packages/documentcloud/base.py", line 181, in save
    self._client.put("{}/{}/".format(self.api_path, self.id), json=data)
  File "/home/bfeldman89/.virtualenvs/mdoc_scraper-Qob3084f/lib/python3.8/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/home/bfeldman89/.virtualenvs/mdoc_scraper-Qob3084f/lib/python3.8/site-packages/documentcloud/client.py", line 148, in _request
    self.raise_for_status(response)
  File "/home/bfeldman89/.virtualenvs/mdoc_scraper-Qob3084f/lib/python3.8/site-packages/documentcloud/client.py", line 169, in raise_for_status
    raise APIError(response=exc.response)
documentcloud.exceptions.APIError: 400 - {"title":["This field may not be null."]}
